"""
Compile a GBNF grammar from a single state's output schema.

This is the load-bearing idea in Ondjila. Existing work either constrains decoding
(Outlines, XGrammar, llama.cpp's own JSON-schema mode) or constrains control flow
(LangGraph, Burr, flow engineering) -- but not both at once. Here the state machine
emits a *different* grammar for every state, so at each step the model is physically
incapable of producing anything other than a legal transition for the state it is in.

Two failure classes disappear by construction rather than by validation-and-retry:
unparseable output, and illegal transitions. What remains -- a well-formed action with
the wrong values -- is caught downstream by deterministic verification, which is the
only place it can honestly be caught.

Keep grammars shallow. Measured per-token mask cost on consumer CPU ranges from about
1 ms for a simple grammar to 69 ms for a deeply nested one; at a few tokens per second
the former is free and the latter is not.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Literal

FieldKind = Literal["enum", "boolean", "integer", "date", "text", "id_ref"]

_IDENT = re.compile(r"^[a-z][a-z0-9_]*$")


@dataclass(frozen=True)
class Field:
    """One value the model is allowed to commit at this state."""

    name: str
    kind: FieldKind
    options: tuple[str, ...] = ()          # enum only
    min_value: int | None = None           # integer only
    max_value: int | None = None           # integer only
    max_chars: int = 120                   # text only
    optional: bool = False

    def __post_init__(self) -> None:
        if not _IDENT.match(self.name):
            raise ValueError(f"field name must be a lower_snake identifier: {self.name!r}")
        if self.kind == "enum" and not self.options:
            raise ValueError(f"enum field {self.name!r} needs at least one option")
        if self.kind != "enum" and self.options:
            raise ValueError(f"field {self.name!r} is {self.kind}, options make no sense")
        if self.kind == "text" and self.max_chars > 400:
            # A long free-text field defeats the point: it is an unconstrained hole
            # in the middle of a constrained grammar, and the model will wander into it.
            raise ValueError(f"text field {self.name!r} exceeds the 400-char ceiling")


@dataclass(frozen=True)
class StateSchema:
    """The complete set of actions legal at one state."""

    state_id: str
    fields: tuple[Field, ...]
    transitions: tuple[str, ...]           # ids of states reachable from here
    allow_abstain: bool = True             # model may say it cannot decide


def _gbnf_string_literal(value: str) -> str:
    """A JSON string literal, escaped for embedding in a GBNF rule."""
    return json.dumps(value).replace("\\", "\\\\").replace('"', '\\"')


def _rule_for_field(f: Field) -> tuple[str, list[str]]:
    """Return (rule reference, [rule definitions]) for one field's value."""
    rule = f"val-{f.name.replace('_', '-')}"
    defs: list[str] = []

    if f.kind == "enum":
        alts = " | ".join(f'"\\"{opt}\\""' for opt in f.options)
        defs.append(f"{rule} ::= {alts}")

    elif f.kind == "boolean":
        defs.append(f'{rule} ::= "true" | "false"')

    elif f.kind == "integer":
        # Bound the digit count so the model cannot emit a 40-digit number.
        hi = f.max_value if f.max_value is not None else 9999
        digits = max(1, len(str(abs(hi))))
        defs.append(f"{rule} ::= [0-9]{{1,{digits}}}")

    elif f.kind == "date":
        defs.append(f'{rule} ::= "\\"" [0-9]{{4}} "-" [0-1][0-9] "-" [0-3][0-9] "\\""')

    elif f.kind == "id_ref":
        defs.append(f'{rule} ::= "\\"" [a-z] [a-z0-9_.]{{0,63}} "\\""')

    elif f.kind == "text":
        # Deliberately excludes the double quote and backslash so the JSON cannot break.
        defs.append(f'{rule} ::= "\\"" [^"\\\\]{{0,{f.max_chars}}} "\\""')

    else:  # pragma: no cover - FieldKind is exhaustive
        raise ValueError(f"unknown field kind: {f.kind}")

    return rule, defs


def compile_state_grammar(schema: StateSchema) -> str:
    """Compile one state into a GBNF grammar.

    The model emits a single JSON object: the fields it committed, plus the transition
    it chose. Both are closed sets. There is no `additionalProperties` hole and no
    free-form action string.
    """
    if not schema.transitions:
        raise ValueError(f"state {schema.state_id!r} has no transitions; it cannot be entered")

    lines: list[str] = [
        f"# state: {schema.state_id}",
        "# generated by ondjila engine.grammar -- do not edit by hand",
        "",
    ]

    required = [f for f in schema.fields if not f.optional]
    optional = [f for f in schema.fields if f.optional]

    parts: list[str] = ['"{" ws']
    field_defs: list[str] = []

    for i, f in enumerate(required):
        ref, defs = _rule_for_field(f)
        field_defs.extend(defs)
        sep = ' "," ws' if i > 0 else ""
        parts.append(f'{sep} "\\"{f.name}\\"" ws ":" ws {ref} ws')

    for f in optional:
        ref, defs = _rule_for_field(f)
        field_defs.extend(defs)
        parts.append(f'( "," ws "\\"{f.name}\\"" ws ":" ws {ref} ws )?')

    # The transition is always present and always closed.
    sep = ' "," ws' if required or optional else ""
    parts.append(f'{sep} "\\"next\\"" ws ":" ws transition ws "}}"')

    lines.append("root ::= " + " ".join(parts))
    lines.append("")

    targets = list(schema.transitions)
    if schema.allow_abstain:
        targets.append("__abstain__")
    lines.append("transition ::= " + " | ".join(f'"\\"{t}\\""' for t in targets))
    lines.append("")
    lines.extend(sorted(set(field_defs)))
    lines.append("")
    lines.append('ws ::= [ \\t\\n]*')

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    demo = StateSchema(
        state_id="ao.identidade.parents_documented",
        fields=(
            Field(
                name="parents_have_id",
                kind="enum",
                options=("ambos", "apenas_mae", "apenas_pai", "nenhum", "nao_sei"),
            ),
            Field(name="birth_year", kind="integer", min_value=1900, max_value=2026),
        ),
        transitions=("ao.identidade.route_standard", "ao.identidade.route_late"),
    )
    print(compile_state_grammar(demo))
